CFLAGS= -Wall -fpic -coverage -lm -std=c99

testme: testme.c
	gcc -o testme testme.c -g $(CFLAGS)

testing:
	echo "Random Testing Quiz"
	echo "testme output:"
	make testme
	./testme

clean: 
	rm -f *.o *.gcov *.gcda *.gcno *.so